### ISSUE TITLE
Send file

### ISSUE THREAD

**Issue by jodosha** [lotus/controller#102]
Add a `send_file` method to actions, in order to send files to HTTP clients.
Quick and dirty implementation available at: https://github.com/lotus/controller/tree/send-file

**Comment by jodosha** [comment]
@AlfonsoUceda Would you love to take care of this? If possible I'd release v0.4.3 by Friday.

**Comment by AlfonsoUceda** [comment]
Ok @jodosha ;) I'll take of it

**Comment by jodosha** [comment]
@AlfonsoUceda You're a machine :yellow_heart: :green_heart: :blue_heart:
