### ISSUE TITLE
Wrong format on Internet Explorer

### ISSUE THREAD

**Issue by gotjosh** [lotus/controller#104]
Howdy fellow lotus lovers!

I noticed that two of my Lotus Production apps won't allow Internet Explorer access. They would immediately throw a 500 error when trying to access them. After some digging, these are my findings:

The `HTTP_ACCEPT` header that IE (short for Internet Explorer from now on) is coming with; is `text/html, application/xhtml+xml, image/jxr, */*` when checking `self.format` inside an controller action we can see that this translates to `:'123'`. Weird right?

After digging around in `lotus/controller` I noticed this particular method inside [mime.rb](https://github.com/lotus/controller/blob/master/lib/lotus/action/mime.rb#L418)

````ruby
def accepts
  unless accept == DEFAULT_ACCEPT
    ::Rack::Utils.best_q_match(accept, ::Rack::Mime::MIME_TYPES.values)
  end
end
````

Since `accept` is equal to `HTTP_HEADER` the result from Rack's `best_q_match` is `"application/vnd.lotus-1-2-3"` (more info on this [here](https://www.iana.org/assignments/media-types/application/vnd.lotus-1-2-3)) which is what is ultimatetly determining the not-so-cool `:'123'` format.

# SIDENOTE
I took a few side steps onto Rack to check out this [function](https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L200-L224) and this is the result from `q_values` for this particular string:

`[["text/html", 1.0], ["application/xhtml+xml", 1.0], ["image/jxr", 1.0], ["*/*", 1.0]]`

Seems weird that the quality of all of them is 1.0 considering that `text/html` should be the one to be respected, in particular `*/*` is the one being extrapolated to `"application/vnd.lotus-1-2-3"`, I know that our very own @jodosha patched this function and added a test case that involves this particular string so I believe something broke in Rack along the way. You can take a look at @jodosha's patch [here](https://github.com/rack/rack/commit/e06a25423979e0443e6252cbe0cb4b2b41fa89f0)

I want to help out here, so my question is, is this something that should be patched/fixed in Lotus or completely delegate this to Rack? It's believe is quite bad for us (Lotus) that IE is broken out of the box.

**Comment by jodosha** [comment]
@gotjosh Hello and thanks for reporting this problem. I'm going to investigate and decide what to do. It's a blurry line between Rack and Lotus::Controller :smile_cat:

**Comment by jodosha** [comment]
@gotjosh I'm a confused. First of all, I've introduced a test to verify the failure that you've reported, but it's passing without changing a line in the production code (see https://github.com/lotus/controller/commit/31e929b395acaea11340c47da53274372d70c1e4). From this perspective looks like a "non-bug".

However, wrong `format` causes a wrong `Content-Type` response header sent to the browser. How this can cause a server side error?

You have referenced a Rack patch, are you using 1.6.0?

Can you please share the stack trace? Thank you very much.

**Comment by jodosha** [comment]
@gotjosh There is one problem here: the build fails on Ruby 2.0+ (2.2 excluded). https://travis-ci.org/lotus/controller/builds/61126011

I suspect you're on 2.0 or 2.1, correct?

**Comment by gotjosh** [comment]
Hi @jodosha! It's a quite blurry line if you ask me, that's why I wanted to ask first. Allow me to respond in order:

1) Yes, indeed a wrong `format` causes a wrong `Content-Type` and therefore the template that you're going to render is not found which causes the "server side" error during rendering phase. 

2) I am using rack 1.6, here's the stack trace:

![stack-trace](https://www.evernote.com/shard/s81/sh/04f162b2-a010-4346-b604-c61aa16da564/3a116f4afb1d13daffacf83ba4bd242b/res/a450b045-e9ea-4595-a97c-c737cb07efa3/skitch.png)

3) Yep, I'm on 2.1.2 and the build matrix seems about right. In you take a look it's stating that the format is `123` which comes from the lotus interpretation of `application/vnd.lotus-1-2-3` which is what rack is returning. Seems weird that this feature is Ruby related.

**Comment by jodosha** [comment]
This is related to This is related to https://github.com/lotus/controller/issues/59

**Comment by gotjosh** [comment]
Ohhh! I completely missed that rack patch inside lotus/controller :cry:

**Comment by gotjosh** [comment]
However the patch states is only for Rack 1.5 or below, I'm currently on Rack 1.6.

**Comment by jodosha** [comment]
> However the patch states is only for Rack 1.5 or below, I'm currently on Rack 1.6.

True, but I just discovered that `Rack.release` is broken on `1.6.0`: it still returns `"1.5"`. See https://github.com/rack/rack/issues/751 and https://github.com/rack/rack/pull/777

**That patch was always applied** :scream: That means Rack 1.6 still has a bug in the MIME type handling.

The last commit above should fix the build for all the supported Rubies.

**Comment by gotjosh** [comment]
Fantastic! :shipit:

**Comment by jodosha** [comment]
@gotjosh Can you please verify that `master` now fixes your app? If so, I'll be happy to do a patch release for this.

**Comment by headius** [comment]
The logic you've applied here is fragile and will probably break again in the future...because it is patching around differences in sort implementations.

In jruby/jruby#3004, we have an issue caused by the way our sort implementation handles equivalent entries. A test case in Lotus uses an accept specification with two equivalently-weighed mime types, and then expects that they'll be ordered the same across all Ruby implementations. Unluckily for us, JRuby differs: https://github.com/jruby/jruby/issues/3004#issuecomment-106826444

It's also interesting that prior to 19345cc6cc33c31248b91e005d809ae0399e72b9, Rubinius was treated as an odd man out.

There's a fundamental issue here with the way the weighted sorting is done; you're going to see sort implementations vary over time and across Ruby implementations, and the way they sort equivalent entries will cause this to break again and again. I would suggest that you add some additional weighting based on the position in the accept list, so equivalent entries won't be quite so equivalent.

**Comment by jodosha** [comment]
@headius THB, I'm not proud of that patch. Another poor quality indicator is the high churn in this area.

That being said, we wanted to borrow from `Rack::Utils` as much as possible. As they should cover most of the edge cases that come from browsers quirks. Until few months ago (can't recall if pre MRI 2.2 or Rack 1.6), the order of the returned entries was following their order of apparence.

It suddenly broke and we had to reverse. :cry: It deserves a solid implementation, I'm gonna to rewrite it and send a PR to the Rack team.

Thanks for having a look at our builds. :100:
