### ISSUE TITLE
Lotus::Utils::Hash conflicts with ActiveSupport::HashWithIndifferentAccess.new

### ISSUE THREAD

**Issue by weppos** [lotus/controller#106]
First of all, let me say that I'm reporting the issue as it is (since it took me a while to understand what was going on) and it may not necessarily be an issue on your side. However, I'd like to start the discussion to figure out what is the best approach here.

I have an object, which performs some Hash manipulation. The input is a controller parameter, and since I'm using both Rails and Lotus, the object can be either a Lotus `Params` instance or a `Hash` (in case of Rails).

To avoid incompatibilities, the initializer calls `to_h` on the input, to make sure to work with a simple hash rather subclasses or specific implementations.

```ruby
class ContactParams
  def initialize(params)
    @params = params.to_h
  end

  def to_h
    @params.slice(...)
  end
end
```

To make sure I can always reference the `Hash` with a symbol, but to bypass the symbol GC issue in Rails < 2.2 I'm using the `ActiveSupport::HashWithIndifferentAccess.new` class.

```
class ContactParams
  def initialize(params)
    @params = ActiveSupport::HashWithIndifferentAccess.new(params.to_h)
  end
end
```

Here comes the problem. Have a look at this console log

```
(byebug)  ActiveSupport::HashWithIndifferentAccess.new(Lotus::Utils::Hash.new({ foo: "bar" }))
{}
(byebug) ActiveSupport::HashWithIndifferentAccess.new({ foo: "bar" })
{"foo"=>"bar"}
```

Because `params.to_h` returns an instance of `Lotus::Utils::Hash` and not `Hash`, when the instance is passed to `HashWithIndifferentAccess`, for some reason the resulting object is `{}` (the values are wiped out).

As I mentioned, I still need to debug at which level the values are lost and who is the guilty.

**Comment by weppos** [comment]
Unfortunately, I believe this is not an issue on Lotus side, or not completely. Here's `ActiveSupport` initialization code

```
def initialize(constructor = {})
  if constructor.is_a?(Hash)
    super()
    update(constructor)
  else
    super(constructor)
  end
end
```

An instance of `Lotus::Utils::Hash.new` does not inherit from `Hash`, hence `Hash.new()` is called passing the instance of the Lotus-wrapped Hash. [The result](http://ruby-doc.org/core-1.9.3/Hash.html#method-c-new) is an empty `Hash` where the default value for a key is the Lotus object.

I think I will need to follow a different route, such as create an empty `ActiveSupport::HashWithIndifferentAccess.new` and merge the `params.to_h` into it.

**Comment by jodosha** [comment]
@weppos FYI - `Lotus::Action::Params` provides indifferent access, GC symbol attack protection and safe API to access nested parameters. Is there any specific need to still use AS' Hash?

Probably our `#to_h` should return an instance of `Hash`, so it will guarantee interoperability with other libs.

**Comment by weppos** [comment]
@jodosha I'd like the implementation of our library to be independent from any framework `Params` implementation. The only reason I used the `ActiveSupport::HashWithIndifferentAccess.new` is because AS is potentially a dependency that I can have regardless the use of Rails. If `Hash` would be with indifferent access, I would have never used any AS library at all.

**Comment by jodosha** [comment]
@weppos That means when you'll upgrade to MRI 2.2, you won't use AS anymore, but only invoke `#to_h` on the argument?

Regardless of your answer, I still think it's a good idea to let both `Params` and `Utils::Hash` implementations of `#to_h` to return an instance of `Hash`.

**Comment by weppos** [comment]
> @weppos That means when you'll upgrade to MRI 2.2, you won't use AS anymore, but only invoke #to_h on the argument?

No, unless I have guarantees that the input will always be indexed with Symbols.

**Comment by jodosha** [comment]
Fixed by https://github.com/lotus/controller/commit/e69fadc5f387dab17cfd77266ed2cd4072fc1383

**Comment by weppos** [comment]
Lovely... I just discovered a new issue with Rails 4.2 #facepalm

```ruby
2.1.5 :001 > ActionController::Parameters.new(foo: 1)
 => {"foo"=>1}
2.1.5 :002 > ActionController::Parameters.new(foo: 1).to_h
 => {}
```

**Comment by jodosha** [comment]
@weppos Does it has anything to do w/ Lotus? Or is it just for the record? :smile:

**Comment by weppos** [comment]
When you are feeling sad because you believe your code is terrible... well, come here and you'll feel better.
