### ISSUE TITLE
should default_format :json also force self.format = :json?

### ISSUE THREAD

**Issue by theocodes** [lotus/controller#111]
Currently the response format does not follow `default_format`. 
Maybe it should use `default_format` for response also and the user should have to override if they want something other then the default?

**Comment by g3d** [comment]
:+1: for that

**Comment by joneslee85** [comment]
@theocodes make it happen

**Comment by theocodes** [comment]
Cool. Will take care of it on the weekend.

**Comment by theocodes** [comment]
Just an update – I did not forget this! got a bit busy last week but I intend to get it done asap!

**Comment by joneslee85** [comment]
thx for the update

**Comment by theocodes** [comment]
I've been investigating this the last couple of days and I'm convinced this is not an issue. 

After running some tests i gathered that the responses* seem identical between when I set `self.format = :json' in the action context and when i don't and rely on the `default_format` setting.

* code, headers and body.

However, there is some "weird" behaviour I haven't yet identified with these 2 approaches. I'll continue to investigate it this week and will report back once i've reached a more clear conclusion.

* For the curious * 

I've noticed that with the "JSON Formatter" chrome extension, when i set `default_format :json` on a lotus application's configure block, the response will sort of look like json but it's rendered (by the extension) as text. However, if i manually set `self.format = :json` inside the action.call method execution, it (again, the extension) renders it as json. 

As this could be a limitation of the extension, I will need to investigate further.

Please let me know if anybody came across this issue.

Thanks

**Comment by theocodes** [comment]
So..

After further investigation and thought I concluded 2 things:

1) The action is doing exactly what it's supposed to do and `default_format` should not take precedence over the detected content type. It its there purely so that if the framework cant tell what content-type from the request, it has something to fall back to. And that is already the case.

2) There should be (in my opinion) a separate property in configuration Eg `force_format :json` that discards content-type defaults and detection. The detection is useful for applications that serve multiple types of content and like I mentioned above, the `default_format` is a fallback. I would like to be able to explicitly say, this is an JSON API that returns nothing but JSON. And something tells me this is not an edge case.

This is a simple implementation which I can take care of fairly quickly, but as it would be adding something new to the configuration api, I don't want to do anything until the idea is green lit.

It would look something like this:

``` ruby
# lib/lotus/action/mime.rb#187

...

  def content_type
    @content_type || forced_content_type || accepts || default_content_type || DEFAULT_CONTENT_TYPE
  end

  def forced_content_type
    self.class.format_to_mime_type(configuration.force_format) if configuration.force_format
  end
...

```

This way setting `self.format = :xml` would still take precedence for exceptional cases but `forced_content_type` would then come above type detection.

It's also worth noting that it is possible to implement this logic currently by creating a separate module that calls `self.format = :json` and including it in every controller. However, while it does work, i feel that creating an extra module for that is overkill and non intuitive. 

Please let me know

**Comment by jodosha** [comment]
@theocodes This is exactly what we need. Thank you :+1: 

Notes about naming:

  1. `forced_content_type`: we use `format` to indicate a Ruby symbol that represents a MIME Type (eg. `:json` for `application/json`), while `content_type` is the textual representation (eg. `"application/json"`). In all the configurations, devs always use formats over content types. See `.default_format`, `.accept`, `#format=` et all.. For consistency, it should be `forced_format` instead.

2. `default` and `forced` don't communicate the intent. They operate on the input and the output, respecitvely. What if we name them `default_request_format` and `default_response_format`?

/cc @lotus/core-team

**Comment by jodosha** [comment]
@theocodes Do you have the time to implement this? Thank you very much :+1:

**Comment by theocodes** [comment]
Sounds good! Leave it with me, I'll take care of it :+1:

**Comment by jodosha** [comment]
@theocodes One last thing, please make sure to graceful handle the transition from `default_format`, by deprecating it etc.. Please see Lotus::Utils for deprecation facility.

**Comment by theocodes** [comment]
sure thing! :+1:
