### ISSUE TITLE
Lotus::Controller and unicorn -  Action status codes persist to next HTTP request.

### ISSUE THREAD

**Issue by baob** [lotus/controller#130]
Our app uses Lotus::Controller and Lotus::Routes, and our production setup uses unicorn.

What we're finding is that if one of the unicorn workers runs an action that explicitly sets a status code ( 500 in our case ) all subsequent HTTP requests that go through the same action and same worker, which do not set a status code, finish with the previously set 500. 

Our workaround is to explicitly set status codes in our actions, including 200. However I would have expected that the default, when status code not set, would be 200 however, and the lotus docs seem to suggest that, there are plenty of examples that do not set a status 200.

**Comment by jodosha** [comment]
@baob Hey thanks for reporting this. Are you using `lotus-controller` as standalone component or inside a Lotus app?

Actions are mutable, in order to make your application safe you must use a new instance for each request. This is handled for you by `lotusrb`, but not if you use `lotus-controller` alone.

Please let me know.

**Comment by baob** [comment]
We are using the two gems (Controller and Router) standalone, we are not using the full lotus app. Can you point me in the right direction please ? I read something yesterday about mutable actions, but what I read suggested that Router would create a new instance every time, so I thought it would not apply to our situation.

This is our routing code:
``` ruby
          Lotus::Router.new do
            get '/subjects/:subject_slug',       to: Actions::SubjectsShow
          end
```

**Comment by jodosha** [comment]
@baob 

You have two solutions:

  * You can add a class method for each action `.call` and do:

```ruby
def self.call(env)
  new.call(env)
end
```

  See more at: https://github.com/lotus/controller#thread-safety

  * Or you can on action naming syntax (`to: 'actions#subjects_show`)
