### ISSUE TITLE
with session + cookie enabled, set-cookie header for rack.session is sent twice

### ISSUE THREAD

**Issue by pascalbetz** [lotus/controller#138]
When having ```cookies``` and ```sessions``` enabled, then the __set-cookie__ header for __rack.session__ is sent twice, once with and once without __path__.
This leads to confusing state when modifying session content.

Steps to reproduce:

1) create a new lotus app
2) modify files as follows
```ruby
# application.rb: enable cookies AND sessions
...
cookies true
sessions :cookie, secret: 'verrrrrry-secret'
..

# routes.rb
get '/', to: 'home#index'

# web/controllers/home/index.rb
module Web::Controllers::Home

  class Index
    include Web::Action

    def call(params)
      self.body = 'Welcome'
    end
  end
end
```
3) lotus server
4) visit localhost:2300 and check response headers, you'll see

```
Set-Cookie:rack.session=BLA...BLA; HttpOnly
Set-Cookie:rack.session=BLA...BLA; path=/; HttpOnly
```

First cookie is from ```cookies``` second one from ```sessions```

Problem can be "fixed" by setting the __path__ of ```cookies``` to the same value as the __path__ of ```sessions``` but still two headers with same content are sent back to the browser.

**Comment by pascalbetz** [comment]
For completeness:

```ruby
cookies path: '/'
sessions :cookie, secret: ENV['WEB_SESSIONS_SECRET'], path: '/'
```

should fix the problem until it is solved within the framework.

**Comment by camelspeed** [comment]
@pascalbetz I am confirming that the workaround works for me (thanks!) and I am now able to get beyond my session issues.  For others to read: basically one of the sessions was being discovered for any URLs of depth >= 2 (i.e. ```http://myapp:2300/one/two```), which caused me to either not be logged out, sometimes incorrectly logged out, and, also, my ```flash[:alert]``` messages being lost

One other note: it appears the ```sessions``` setting defaults to the ```path: '/'``` value while the ```cookies``` defaults to no path.  So it appears that only the suggested ```cookies path: '/'``` is needed but perhaps having both makes it the intent explicit that they must be equal until the proper framework fix is in.

**Comment by jodosha** [comment]
@AlfonsoUceda This is related to path prefixes inside Container apps. Because you already worked on this specific part, would you help to fix it?

---

When we initialize `Lotus::Container::Router`, we instantiate Lotus apps subclasses and [pass the path prefix](https://github.com/lotus/lotus/blob/master/lib/lotus/container.rb#L9) as an argument.

Then at the loading time, we can specify the path prefix for both [cookies](https://github.com/lotus/lotus/blob/master/lib/lotus/loader.rb#L69) and [sessions](https://github.com/lotus/lotus/blob/master/lib/lotus/middleware.rb#L126). Because in both the contexts we have an instance of the application around, we can use `Configuration#path_prefix` and use it specify the `:path` option, as explained by @pascalbetz above.

**Comment by pascalbetz** [comment]
@jodosha 

Even with the same path set, the cookies are sent twice! This is clearly a bug Lotus should not send multiple set-cookie headers for the same content.
Actually if the __cookies__ would not send __rack.session__ then everything would work as expected. So to me the fix is not aligning the paths but to make sure that the session cookie is only sent once.

**Comment by camelspeed** [comment]
I took a closer look at the 2 cookies (rack.session) being set and noticed that the values for the same key are **not always** the same even with the workaround.  See the Response Headers below.
'''Request URL:http://localhost:2300/login
Request Method:GET
Status Code:302 Found
Remote Address:[::1]:2300
Response Headers
view source
Content-Security-Policy:default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self';
Content-Type:text/html; charset=utf-8
Location:/
**Set-Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTJmM2NhNmVmMDRkZmYxNWRjMzFl%0ANjcxMmE1ZWMwY2UzZTUxN2EzZmRhMDgxMjNiN2U1YzAzMjM5OTYwNzZiZDUG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYjY3ZjZhNDBhYzI3Yjk5MTQyNjRi%0ANzg4MDEwMjlhMTVmYWVhY2RjYTE1M2Y3NDEzYTg2OTc3ODI5NDM0MTc2NQY7%0AAEY%3D%0A--e2c2515abe8451f12333317a66eb0fbd9ceb0910; path=/; HttpOnly**
**Set-Cookie:rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTJmM2NhNmVmMDRkZmYxNWRjMzFl%0ANjcxMmE1ZWMwY2UzZTUxN2EzZmRhMDgxMjNiN2U1YzAzMjM5OTYwNzZiZDUG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYjY3ZjZhNDBhYzI3Yjk5MTQyNjRi%0ANzg4MDEwMjlhMTVmYWVhY2RjYTE1M2Y3NDEzYTg2OTc3ODI5NDM0MTc2NQY7%0AAEZJIgx1c2VyX2lkBjsARmkG%0A--4158e99a752aa62490ff6ead2def1d694a2a0cd5; path=/; HttpOnly**
Transfer-Encoding:chunked
X-Frame-Options:DENY
'''

**Comment by AlfonsoUceda** [comment]
I have the following behaviour:
1) `sessions :cookie, secret: ENV['WEB_SESSIONS_SECRET']`
First request:
```
Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTFiN2MyMDc2YWI3NjliOGZmN2Vl%0AMTBjYmM0ZTc3MzVjMjkzODA0NTg5OTM0OWYzY2VmZGEzMjQ5NDRjNTgyNzgG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFNzQyMGYxZjA5ZDM3MDhkYTc0M2Q1%0AYjM4MTZiZDU0MDIzOTE3YzQ5ZjVkYmU4MWIxMGU5ZmNhOGE1MjFkNzU2ZAY7%0AAEY%3D%0A--beb91a627f399456480d4131a876775b0e9bc8c1
```
Second request:
The cookies is set in Request headers and there isn't `Set-Cookie` in Response headers.

2) `sessions :cookie, secret: ENV['WEB_SESSIONS_SECRET']` and  `cookies true`
First request:
```
Set-Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTBmNGZmOGY5NWNmMGU5M2FkYzhm%0AMGY3NDNkNmVlNDA1NzM2MGZlZWQ1ZThiMmY4NzQxZjVjMDU3YmE3MzExZTMG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYzEzMTE4ZGFkODYzYmE5YjVhMzQ4%0ANDdlMmM0NTI5NzZiMTAxMGFmYmMxMjdmY2Q1OTU3N2FiMDE5NmMyNTY4NAY7%0AAEY%3D%0A--2c209d121c6194a4574f83a88f5c8fa4e5128e31; path=/; HttpOnly
```
Second request:
```
Set-Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTBmNGZmOGY5NWNmMGU5M2FkYzhm%0AMGY3NDNkNmVlNDA1NzM2MGZlZWQ1ZThiMmY4NzQxZjVjMDU3YmE3MzExZTMG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYzEzMTE4ZGFkODYzYmE5YjVhMzQ4%0ANDdlMmM0NTI5NzZiMTAxMGFmYmMxMjdmY2Q1OTU3N2FiMDE5NmMyNTY4NAY7%0AAEY%3D%0A--2c209d121c6194a4574f83a88f5c8fa4e5128e31; HttpOnly
Set-Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTBmNGZmOGY5NWNmMGU5M2FkYzhm%0AMGY3NDNkNmVlNDA1NzM2MGZlZWQ1ZThiMmY4NzQxZjVjMDU3YmE3MzExZTMG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYzEzMTE4ZGFkODYzYmE5YjVhMzQ4%0ANDdlMmM0NTI5NzZiMTAxMGFmYmMxMjdmY2Q1OTU3N2FiMDE5NmMyNTY4NAY7%0AAEY%3D%0A--2c209d121c6194a4574f83a88f5c8fa4e5128e31; path=/; HttpOnly
```
and in request headers I have the `Cookie` header:
```
Cookie:rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiRTBmNGZmOGY5NWNmMGU5M2FkYzhm%0AMGY3NDNkNmVlNDA1NzM2MGZlZWQ1ZThiMmY4NzQxZjVjMDU3YmE3MzExZTMG%0AOwBGSSIQX2NzcmZfdG9rZW4GOwBGSSJFYzEzMTE4ZGFkODYzYmE5YjVhMzQ4%0ANDdlMmM0NTI5NzZiMTAxMGFmYmMxMjdmY2Q1OTU3N2FiMDE5NmMyNTY4NAY7%0AAEY%3D%0A--2c209d121c6194a4574f83a88f5c8fa4e5128e31
```
Third request and followings:
We are sending `Set-Cookie` the same as above but we shouldn't send them.

I cleared cookies between case 1 and 2.

**Comment by AlfonsoUceda** [comment]
Hi guys, I created a branch fixing the problem:
https://github.com/lotus/controller/tree/fix-sessions-and-cookies

could you take a look? I'll create the PR tomorrow.

**Comment by pascalbetz** [comment]
@AlfonsoUceda 

This would also skip cookies that have RACK_SESSION_KEY as value. Or as one of the keys. I think a more "surgical" method would be better.

**Comment by AlfonsoUceda** [comment]
@pascalbetz session is handled by `Rack::Session::Cookie` middleware
