### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by jodosha** [lotus/controller#23]
WebSocket support! :sparkling_heart: 

Example:

```ruby
module Chat
  class Show
    include Lotus::Action
    include Lotus::Action::WebSocket

    def call(params)
      websocket.on_open do
        send_data "Hi"
      end

      websocket.on_message do |message|
        send_data "Echo: #{ message }"
      end
    end
  end
end
```

The corresponding client side code:

```javascript
document.addEventListener("DOMContentLoaded", function(event) { 
  var socket       = new WebSocket("ws://localhost:2300/chat");
  
  socket.onmessage = function(message) {
    console.log(message);
    window.alert(message.data);
  };
  
  socket.send("Hello");
}
```

**Comment by xiy** [comment]
What happened to @ricardovaleriano's SSE implementation in the end?

**Comment by jodosha** [comment]
@xiy I guess he didn't had the time to experiment/deliver anymore. :smile:

**Comment by jodosha** [comment]
Sadly, we have to postpone this because the implementation based on Rack Hijiack and Puma doesn't scale. Closing this for now. :cry:

**Comment by tak1n** [comment]
@jodosha maybe hanami can adopt https://github.com/palkan/litecable which provides different production variants (go server, erlang server) through https://github.com/anycable/anycable.

For development mode it also uses the rack hijack approach.

Hanami could also provide it's own logic handler if litecable does not fit: https://github.com/anycable/anycable/wiki/Using-AnyCable-with-Ruby-(non-Rails)#custom-backend-framework

**Comment by jodosha** [comment]
@tak1n Thanks for the heads up.

These are great solutions that work out of the box. 👍

**Comment by boazsegev** [comment]
I love the idea of using litecable, even though it requires the ActionCable client (javascript).

As for raw WebSockets, I invite you to help refine the [WebSocket Rack Extension Draft](https://github.com/boazsegev/iodine/blob/master/SPEC-Websocket-Draft.md) in the [iodine server branch](https://github.com/boazsegev/iodine).

I'm the author for the iodine server and I'm working on redesigning the pub/sub layer for the upcoming 0.5.0 release, so it's a good time to incorporate any feature requests.

[Iodine's approach to WebSocket upgrade](https://github.com/boazsegev/iodine/blob/master/SPEC-Websocket-Draft.md#upgrading) is very effective. It also minimizes object creation (no need for multiple Proc objects per connection).

**Comment by boazsegev** [comment]
@jodosha, thank you for allowing me to join the discussion.

> I imagine that Iodine already implements it.

Yes, iodine was implementing variations on these specifications for a number of years and helped gather the experience that tested the API's design.

[The Agoo server](https://github.com/ohler55/agoo) also implements the specifications, though the more established servers (such as Puma and Passenger) are still considering the specification.

> Did you discuss with other Ruby Rack server people and/or Rack folks to gather feedback and try to understand if they want to adopt your proposal?

There were a number of attempts to solidify this specification and the latest discussion can be reviewed in the [Rack PR#1272 thread](https://github.com/rack/rack/pull/1272).

The discussion was locked for being "too heated", but the general feeling was positive.

Evan Phoenix (Puma) was generally positive about the suggestion, but [had some reservations](https://github.com/rack/rack/pull/1272#issuecomment-385825312) that were addressed by changes to the proposal.

I also authored [a Rails PR to include support for the specifications ActiveCable](https://github.com/rails/rails/pull/33295) to follow up with the summery of the discussion.

> What's the usual client side library that you suggest to use with Iodine. I know it can be anything, but that do you recommend? Thanks.

I'm partial to raw WebSockets and custom authored solutions. I find that many libraries mutate too often with time and become harder to adjust as projects grow.

Also, the basic JavaScript API is easy enough and routing JSON messages and events is often a breeze. The only thing to watch is probably the reconnection concerns.

Having said that, the interface for LiteCable and ActionCable appears to have a stable design that works. I'm not in love with the implementation for ActionCable (to say the least), so I would probably go with LiteCable if I had to choose between the two.

**Comment by jodosha** [comment]
@boazsegev 
> I would probably go with LiteCable if I had to choose between the two.

Do you mean that a) you'd pick LiteCable as a user that wants to build WS with Iodine or b) Iodine will work out of the box with LiteCable JavaScript code?

Sorry if the question is silly, but I'm not familiar with Iodine. Thanks. 👍

**Comment by boazsegev** [comment]
@jodosha 

I meant that I'd pick LiteCable as a user that wants to build WS with Iodine.

Iodine doesn't enforce any WebSocket sub-protocol on the user. It supports raw WebSockets to allow for maximum flexibility and separation of concerns.
