### ISSUE TITLE
Make parameter types required

### ISSUE THREAD

**Issue by stevehodgkiss** [lotus/controller#67]
For example, `param :id, Integer`

Coercing user input into an expected type is a good practice. Without specifying a type, based on what the parser in rack gives you, you could end up with a string, array, hash, nil or a tempfile. It would be great if lotus made developers think about this and provided guarantees that the parameter would be either the given type or nil.

Rails has had vulnerabilities in the past that would have been non-issues if the input was coerced into an expected type before passing it along to ActiveRecord [1].

Thoughts?

[1] https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-security/t1WFuuQyavI

**Comment by Emily** [comment]
I'd be a huge fan of this change (even if it's only required by default). However, I think #53 would have to be done first.

**Comment by jodosha** [comment]
@Emily I'd love to hear more about your use case and why do you think it should be the default.

RE #53 is about to be implemented: see #71

**Comment by Emily** [comment]
@jodosha I've seen many times where developers have simply forgotten to properly whitelist and coerce request parameters. Making whitelisting and coercing required by default prevents that issue.

Very occasionally there may be some reason that very little to no whitelisting can be done (perhaps there's some endpoint that allows an API consumer to store arbitrary data). In those cases allowing the requirement to be disabled is useful. Of course, if there's some per-action configuration that can disable the behavior, e.g.:

```ruby
class SomeAction
  ...
  disable_strict_params!
  ...
end
```

there is always the possibility that a developer puts that in temporarily and forgets to do proper filtering, but there's only so much we can do, and encouraging developers to think about whitelisting/coercing params by making it default would go a long way.

**Comment by jodosha** [comment]
@Emily Thanks for your explanation. I agree that this is a good practice but make it mandatory is an overhead for developers that I don't want to add to the framework.

From real world applications that we are building, params aren't handled by Lotus at all.
Some of them are HTTP API apps that demand to already in place objects to filter those. Other will prefer to delegate this responsibility to Interactors (aka Service Objects), for the sake of DRY the code and let it to be reused by several consumers like Web app, HTTP API, background workers, console.

I think that @stevehodgkiss idea is different: if and only if a developer whitelists params, only in that case she or he must declare a Ruby type.

**Comment by stevehodgkiss** [comment]
@jodosha yes, that's what I had in mind, only mandatory if you're whitelisting (with a `params` block).

@Emily if a developer doesn't want to coerce params, they could simply omit the `params do` whitelisting block and access the unfiltered params hash directly.

**Comment by joneslee85** [comment]
@stevehodgkiss ping, any update?

**Comment by jodosha** [comment]
Stale discussion, I'm closing this for now.
