### ISSUE TITLE
Rack middleware is not working correctly

### ISSUE THREAD

**Issue by benedikt** [lotus/controller#72]
The current implementation of `Lotus::Action::Rack.use` doesn't support passing the app to the middleware. To allow intercepting of requests and responses, Rack middleware is usually implemented like this:

```ruby
class Middleware
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env)
  end
end
```

The current middleware implementation just passes the `env` to the middleware's `call` method and therefore doesn't work with middleware that might stop the execution of the middleware stack or modify the request or the response.

A reference implementation of Rack middleware can be found in Rack itself:

1. https://github.com/rack/rack/blob/master/lib/rack/builder.rb#L81-L87
1. https://github.com/rack/rack/blob/master/lib/rack/builder.rb#L144-L154

Thanks a lot!

**Comment by jodosha** [comment]
@benedikt Hello and thanks for reporting this.
I do agree with you: currently we only have an half-backed solution for fine grained rack stacks.

We'll try to accommodate this change soon. Which middleware are you trying to mount?

**Comment by benedikt** [comment]
Hi @jodosha,

thanks for looking into this! At the moment, I'm mostly looking at authentication middleware like warden as well as custom middleware.
I'm happy to help out, but I'm not very familiar with the overall architecture and ideas of this gem, yet.

**Comment by jodosha** [comment]
@benedikt Hey, thanks for the quick reply. Mr @AlfonsoUceda will be in charge of this. We're discussing about details right now.

**Comment by jodosha** [comment]
@benedikt me and @AlfonsoUceda looked at this on yesterday.

We have found a solution, but it still needs to be validated with code.

**Comment by benedikt** [comment]
Nice! Take your time. It's not super urgent :)

**Comment by AlfonsoUceda** [comment]
@benedikt fixed in master in lotus/controller and lotus/router, this will be released soon ;)

**Comment by jodosha** [comment]
@benedikt can you please try by using the following `Gemfile` configuration? Please report if it works or if there are other issues. We want to make sure that this works for you before to release it. Thank you. :hamster: 

```ruby
gem 'lotus-router', github: 'lotus/router'
gem 'lotus-controller', github: 'lotus/controller'
```

**Comment by jodosha** [comment]
I've tested this feature in isolation here: https://gist.github.com/jodosha/685b6369f9aeb1b01bf7

Closing this. @benedikt Feel free to reopen if it doesn't work for you.

**Comment by benedikt** [comment]
I haven't had the time to test it, yet. I'll reopen this issue should I have troubles with it. Thanks a lot everyone!
