### ISSUE TITLE
:handle_exception doesn't work consistently for Action and Controller

### ISSUE THREAD

**Issue by weppos** [lotus/controller#75]
Given the following configuration

```ruby
Lotus::Controller.configure do
  handle_exception ActiveRecord::RecordNotFound => :handle_record_not_found
end
```

and the following handler

```ruby
def handle_record_not_found(exception)
  halt(404, { message: exception.message }.to_json)
end
```

If I define the handler in the action, the code is working as expected. If I define the action in the configure block

```ruby
Lotus::Controller.configure do
  handle_exception ActiveRecord::RecordNotFound => :handle_record_not_found

  def handle_record_not_found(exception)
    halt(404, { message: exception.message }.to_json)
  end
end
```

the code crashes with error

```
Puma caught this error: undefined method `to_i' for :handle_record_not_found:Symbol (NoMethodError)
```

Is this expected? Is there any different between the error handling in the action, and in the configuration?

**Comment by weppos** [comment]
One more thing. Wrapping all into a `prepare` block behaves like Action.

```ruby
Lotus::Controller.configure do
  prepare do
    handle_exception RecordNotFound => :handle_record_not_found

    def handle_record_not_found(exception)
      halt(404, { message: exception.message }.to_json)
    end
  end
end
```

**Comment by jodosha** [comment]
@weppos Thanks for reporting this, but that isn't the way to use `.configure`.
I suggest to use modules: anonymously via `#prepare` or explicitly via the following code:

```ruby
module NotFoundHandler
  def self.included(base)
    base.class_eval do
      handle_exception RecordNotFound => :handle_record_not_found
    end

    def handle_record_not_found(exception)
      halt(404, { message: exception.message }.to_json)
    end
  end
end

Lotus::Controller.configure do
  prepare do
    include NotFoundHandler
  end
end
```

**Comment by weppos** [comment]
@jodosha the inline documentation advertises to use configure `handle_exception` in the controller block. :confused:

**Comment by joneslee85** [comment]
@weppos @jodosha we need to provide more docs & examples.

@weppos It'd be great if you could provide a basic example in code comments. Feel free to re-open this issue. TIA

**Comment by jodosha** [comment]
@weppos Yes, `handle_exception` can be configured in the `.configure` block.

What **isn't allowed** is to define the method inside that block like this.

```ruby
Lotus::Controller.configure do

  # THIS DOESN'T WORK AS EXPECTED ;-)
  def handle_record_not_found(exception)
    halt(404, { message: exception.message }.to_json)
  end
end
```

**Mine was only a suggestion** to keep the exception handling (`handle_exception`) close to the handler definition (`def handle_record_not_found`) in the same module.

**To recap:** `handle_exception` goes inside `.configure`. The action should respond to that method.
