### ISSUE TITLE
Ability to configure a filter in a specific position

### ISSUE THREAD

**Issue by weppos** [lotus/controller#76]
Granted that one of @jodosha's goal was to keep callbacks as simple as possible, I have a case that I feel reveal a reasonable improvement.

Let's assume I have a filter called `authenticate!` that must be run on every action.

```ruby
class Show
  before :authenticate!

  def call(params)
  end
end
```

On a **very few actions** (that's one of the key conditions), let's say 10 out of 100, I need a specific validation to happen before the authenticate.

```ruby
class Index
  before :validate!, :authenticate!

  def call(params)
  end
end
```

I can indeed stick with the explicit example above, but that would mean I can't extract the `before :authenticate!` into a controller config, or a module.

Therefore, I wonder what do you think about providing a finer way to control where I want to add my filter. Right now, there's only a `Chain#add` method.

I propose to add something similar to

- `Chain#append(callback)`
- `Chain#prepend(callback)`
- `Chain#insert(before, callback)` (or `Chain#insert_before(before, callback)` and `Chain#insert_after(after, callback)`)

I can work on a patch, if we agree on naming and API.

**Comment by joneslee85** [comment]
```
I can indeed stick with the explicit example above, but that would mean I can't extract the before :authenticate! into a controller config, or a module.
```

FYI, we could extract common callback to module and include them for every actions by configuring it with `controller.prepapre` block in your `Application` class:

Example:

```ruby
module ApiV1
  class Application < Lotus::Application
    configure do
      controller.prepare do
        include Authentication
        before :authenticate!
      end
    end
  end
end
```

**Comment by weppos** [comment]
Yes, and that's part of the problem. If I extract the `:authenticate!`, then it will be hard to prepend a new filter called `:validalite` before `:authenticate!`, because at the moment filters are only appended and not prepended.

**Comment by jodosha** [comment]
@weppos This is interesting.

`Chain#append` has the same meaning of `Chain#add`. But we can rename it for consistency if introduce the other methods.

Would `Chain#prepend` solve your case?
Then how to express this intent in Action DSL? `prepend_callback :validate!`?

I'm a bit skeptical to add `#insert` and `#insert_after` for two reasons:

  1. I don't see an immediate need. But waiting for @weppos feedback to understand if prepending is enough.
  2. It increases the public API for Action (eg. `.insert_callback`, and `.insert_callback_after`).
  3. It assumes that callbacks are expressed as symbols. We also support anonymous lambdas as callbacks. It's impossible to identify those.

@weppos Can you please verify? So we can decide what to do. Thank you, Sir.

**Comment by weppos** [comment]
Hi @jodosha, let me answer piece by piece.

> `Chain#append` has the same meaning of `Chain#add`. But we can rename it for consistency if introduce the other methods.

Yes, that was my idea.

> Would `Chain#prepend` solve your case?

Yes, at the time being it will solve my case. However, I was trying to thing outside my specific need, for a broader audience.

> I don't see an immediate need. But waiting for @weppos feedback to understand if prepending is enough.

**Comment by weppos** [comment]
Hi @jodosha, let me answer piece by piece.

> `Chain#append` has the same meaning of `Chain#add`. But we can rename it for consistency if introduce the other methods.

Yes, that was my idea.

> Would `Chain#prepend` solve your case?

Yes, at the time being it will solve my case. However, I was trying to thing outside my specific need, for a broader audience.

> I don't see an immediate need. But waiting for @weppos feedback to understand if prepending is enough.

As I said, in my specific case, `prepend` is enough. However, that's because my actions are fairly simple right now and I only have a very limited set of filters.

In a longer chain, however, it may make sense to be able to inject an element in a position relative to another element. If you think, that's the case of the Rack middlewares. Let's suppose I am a plugin writer, I want my plugin to be injected in a Rack stack, but I need my plugin to be executed immediately before another middleware independently if that middleware is the first or is in the middle of the queue. 

Likewise, there may be cases where this makes sense. May be not in the controller, but the `Chain` implementation is generic, therefore it may be useful to add that feature in chain and decide whether we want to expose it or not in controller.

We can also decide to leave just `(prepend|append)_before`, and allow advanced chain manipulations only if you reassign the entire chain. But still, the feature should be in chain to allow an easy item injection.

> It increases the public API for Action (eg. .insert_callback, and .insert_callback_after).

See previous section.

> It assumes that callbacks are expressed as symbols. We also support anonymous lambdas as callbacks. It's impossible to identify those.

Yes, I saw that last day, when I read the `Chain` implementation. To be honest, we can easily set this as a requirement. It's fair to say that you can use `insert` only passing as a pivot a named chain item. 

Again, if I'm right it's exactly how Rack works.

**Comment by jodosha** [comment]
@weppos Thanks for the complete reply.

> Yes, I saw that last day, when I read the Chain implementation. To be honest, we can easily set this as a requirement. It's fair to say that you can use insert only passing as a pivot a named chain item.

The developer who injects the new logic, may be not in control of the original definition of a lambda callback. For instance, imagine a customization on a OSS product like Discourse or Spree, but written with Lotus. The developer can't modify the original code, unless to write some monkey-patching hack.

She or he, won't be able to do this kind of advanced manipulations like `.insert_before_callback_after`.

As usual, I'm keen to include the simplest possible scenario for now.
What if we:

  1. Add `Chain#append` and alias as `#add` for backward compatibility
  2. Add `Chain#prepend`
  3. Expose `.prepend_before` and `.prepend_after` in `Action::Callbacks`
  4. Alias `.before` with `.append_before` in `Action::Callbacks`
  5. Alias `.after` with `.append_after` in `Action::Callbacks`

@weppos are you still available to craft two PRs for Utils and Controller? Thank you!

**Comment by weppos** [comment]
> The developer who injects the new logic, may be not in control of the original definition of a lambda callback. 

Correct. That's why I'm suggesting that we set as a requirement that you can insert only before/after a named callback.

If you have a chain of callback composed by

    [:method_alpha, lambda, lambda, :method_beta, :method_gamma, lambda]

You can call

    insert_before(:method_beta, :method_delta)
    # => [:method_alpha, lambda, lambda, method_delta, :method_beta, :method_gamma, lambda]

    insert_before(:method_alpha, :method_delta)
    # => [:method_delta, :method_alpha, lambda, lambda, method_delta, :method_beta, :method_gamma, lambda]

But you cannot insert a callback before an anonymous lambda callback. 

I researched a little bit the topic and (surprisingly, it's the first time I read it) it's very similar to the [`MiddlewareStackProxy`](http://api.rubyonrails.org/classes/Rails/Configuration/MiddlewareStackProxy.html) behavior.

> @weppos are you still available to craft two PRs for Utils and Controller? Thank you!

Yes. It will take some time. In particular, last time I had to fight with Minitest (I'm an `Rspec` guy ;) ).
