### ISSUE TITLE
Exposures persist between requests?

### ISSUE THREAD

**Issue by ordinaryzelig** [lotus/controller#90]
I noticed that `exposures` doesn't get reset between requests. If the action object is the same between requests, then [exposures being cached via `||=`](https://github.com/lotus/controller/blob/4fafb79b2b58d8ea28be25460f54bd12848e63d8/lib/lotus/action/exposable.rb#L96) will persist between requests as well. In my app, I had to set `@exposures = nil` so that the next time I called `exposures`, it would reload the current state. An example:

```ruby
class Show
  include Lotus::Action
  expose :thing
  def call(params)
    @thing = params[:asdf]
  end
end
show = Show.new
show.call({asdf: 1})
show.exposures.fetch(:thing) #=> 1
show.call({asdf: 'two'})
show.exposures.fetch(:thing) #=> 1

class MyShow
  include Lotus::Action
  expose :thing
  def call(params)
    @exposures = nil # Only difference
    @thing = params[:asdf]
  end
end
my_show = MyShow.new
my_show.call({asdf: 1})
my_show.exposures.fetch(:thing) #=> 1
my_show.call({asdf: 'two'})
my_show.exposures.fetch(:thing) #=> 'two'
```

Is this expected behavior?

**Comment by AlfonsoUceda** [comment]
@ordinaryzelig I believe @exposures doesn't live between request, the `||=` operator is used together `[]` tu push in the array the instance variables.

In your example you instantiate only one time the action and call several time `call` method, In every request the action is instantiate if I am not wrong

**Comment by jodosha** [comment]
@ordinaryzelig Exposures are cached, because an action instance isn't designed to be reused across HTTP requests. When `lotus-controller` is used by `lotusrb` or `lotus-router` they instantiate an action for each new request.

If you are unit testing that action, you should not care about this aspect, because everything is managed by the higher level components of Lotus.

If you are using this framework in standalone mode, you may want define `.call` at the class level:

```ruby
[1] pry(main)> require 'lotus/controller'
=> true
[2] pry(main)> class Show
[2] pry(main)*   include Lotus::Action
[2] pry(main)*   expose :thing
[2] pry(main)*   def self.call(env)
[2] pry(main)*     new.call(env)
[2] pry(main)*   end
[2] pry(main)*   def call(params)
[2] pry(main)*     @thing = params[:asdf]
[2] pry(main)*     headers['X-Exposures-Thing'] = exposures.fetch(:thing)
[2] pry(main)*   end
[2] pry(main)* end
=> :call
[3] pry(main)> Show.call(asdf: 1)
=> [200, {"X-Exposures-Thing"=>1, "Content-Type"=>"application/octet-stream; charset=utf-8"}, []]
[4] pry(main)> Show.call(asdf: 'two')
=> [200, {"X-Exposures-Thing"=>"two", "Content-Type"=>"application/octet-stream; charset=utf-8"}, []]
[5] pry(main)>
```

**Comment by ordinaryzelig** [comment]
Thanks to both of you. I was indeed routing directly to the Action class, not a string. So I defined Action.call as suggested and instantiated manually.
