### ISSUE TITLE
#call method is called even when a before callback does a redirect_to.

### ISSUE THREAD

**Issue by donperi** [lotus/controller#93]
Hi everyone!

I'm experimenting some random behaviors.

I have a `before :authenticate!` callback that redirect to '/login' when a session doesn't exist. Simple.

When making the tests for the action I wanted to check that it returns 302 when user isn't  authenticated.

When running the tests, the tests were running the #call method and calling the Repository when it should stop the chain and redirect.

Here some examples.

```ruby
module Web::Controllers::Posts
  class Index
    include Web::Action
    # include Web::AuthenticatedAction

    before :authenticate!

    def call(params)
      puts  "This should not be called"
    end

    def authenticate!
      puts "Redirect should stop here"
      redirect_to '/login'
    end
  end
end
````

Here is the output when I request the controller route

```sh
[2015-03-09 18:04:15] INFO  WEBrick 1.3.1
[2015-03-09 18:04:15] INFO  ruby 2.1.4 (2014-10-27) [x86_64-darwin14.0]
[2015-03-09 18:04:15] INFO  WEBrick::HTTPServer#start: pid=49653 port=2300
Redirect should stop here
This should not be called
::1 - - [09/Mar/2015:18:04:18 -0400] "GET / HTTP/1.1" 302 - 0.9164
::1 - - [09/Mar/2015:18:04:19 -0400] "GET /login HTTP/1.1" 200 - 0.8267
```

The same apply for tests.

**Comment by gotjosh** [comment]
:+1:

**Comment by luishurtado** [comment]
@donperi what if you set a flag in the before callback and then check for it inside the call method?
If we set as convention (not as a bug) that the call method is always invoked I think we will have controllers more easy to follow and debug. In another words we should give the call method the responsibility of redirect, render, etc... the before callbacks should be responsible for check conditions or whatever and set flags.

**Comment by joneslee85** [comment]
@donperi did you try with `redirect_to :blah and return`?

**Comment by donperi** [comment]
@joneslee85 Yes I tried that. Return the redirect and return false, same result.

@luishurtado It can work but for me I think it's a bad practice. Then we have to maintain all the actions that use those callbacks.

```ruby
before :authenticate

def call(params)
  if @some_before_flag
    # implementation
  end
end

def authenticate!
  @some_before_flag = true
   redirect_to '/login'
end
````
Is this what you trying to explain?

If it is, I think is bad, because we need to add the same code to all actions with that callback.
and if we need another callback with another conditional we need to add the flag the call method.
Also that flag needs to be in others callbacks if we don't want them to execute, and the code will be very confuse.

**Comment by AlfonsoUceda** [comment]
Hi guys, the problem is the ancestors `call` method chain, `call` method in action always is called.

**Comment by luishurtado** [comment]
@donperi the following code explains my point:
```ruby
...
  before :check_authenticated

  def call(params)
    redirect_to '/login' unless @authenticated
    # ... more controller logic here ...
  end

  def check_authenticated
    # .. logic here to check authentication ...
    @authenticated = true # or false depending on the logic
  end
...
```

**Comment by AlfonsoUceda** [comment]
@luishurtado the problem is that call method is called, then if you have method like search in database the code is executed.

A clear example is forbid a page an user without privileges, the call method shouldn't be called, IMO

**Comment by jodosha** [comment]
@donperi Thanks for reporting this issue. I never considered `redirect_to` as a Ruby returning statement. But yeah, it's probably expected by developers to use it as a control flow. :+1: for the fix.

**Comment by gotjosh** [comment]
@jodosha I know it's not on topic but how would you approach similar functionality w/o using `reditect_to` as a returning statement.

**Comment by jodosha** [comment]
@gotjosh Please have a look at `Throwable#halt`.
